sonar.projectKey=labibahhoque-wq_Password-Generator
sonar.organization=labibahhoque-wq

sonar.projectName=Password-Generator
sonar.projectVersion=1.0
sonar.sources=Password Generator/src
sonar.exclusions=**/GeneratorTest.java
sonar.java.binaries=Password Generator/bin
sonar.sourceEncoding=UTF-8
